sudo: required
services:
  - docker

before_install:
  - docker build -t leenverbiest/docker-react -f Dockerfile.dev .

script:
  - docker run leenverbiest/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  region: "Europe"
  app: "mydockerreact"
  on:
    branch: master
  api_key:
    secure: "$HEROKU_API_KEY"  